version: '3.7'

services:
  mongo:
    image: mongo
    ports:
    - 27017:27017
  mongo-ui:
    image: mongo-express
    ports:
    - 8081:8081
    depends_on:
    - mongo
  parties:
    build: web/backend/parties
    ports:
    - "8000:80"
    environment:
    - MONGO_HOST=mongo
  craps:
    build: web/model/craps
    ports:
    - "8020:90"
  frontend:
    build: web/frontend
    ports:
    - "8080:8080"
