version: '3.7'

services:
  mongo:
    image: mongo
    ports:
    - 27017:27017
  mongo-ui:
    image: mongo-express
    ports:
    - 8081:8081
    labels:
    - traefik.enable=true
    - traefik.http.routers.mongo-ui.rule=PathPrefix(`/mongo-ui`)
    - traefik.http.routers.mongo-ui.entrypoints=web
    depends_on:
    - mongo
  parties:
    build: ./parties
    ports:
    - "8000:80"
    environment:
    - MONGO_HOST=mongo
    - PARTIE_HOST=parties
    - PARTIE_PORT=80
    labels:
    - traefik.enable=true
    - traefik.http.routers.parties.rule=PathPrefix(`/parties`)
    - traefik.http.routers.parties.entrypoints=web
    depends_on:
    - mongo
  traefik:
    image: traefik:v2.5
    command:
    - --api.insecure=true
    - --providers.docker=true
    - --providers.docker.exposedbydefault=false
    - --entrypoints.web.address=:80
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
    - 80:80
    - 8085:8085