version: '3.7'

services:
  mongo:
    image: mongo
    ports:
    - 27017:27017
  mongo-ui:
    image: mongo-express
    ports:
    - 8081:8081
    depends_on:
    - mongo
  parties:
    build: ./parties
    ports:
    - "8000:80"
    environment:
    - MONGO_HOST=mongo
  cors:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: cors
    ports:
      - "4545:80"
