[entryPoints]
  [entryPoints.web]
  address = ":80"

  [entryPoints.websecure]
  address = ":443"

  [entryPoints.dashboard]
    address = ":9090"

[api]

[providers.docker]
  endpoint = "unix:///var/run/docker.sock"

[certificatesResolvers.letsencrypt.acme]
  email = "thrawn.1809@gmail.com"
  storage = "acme.json"
  [certificatesResolvers.letsencrypt.acme.httpChallenge]
    entryPoint = "web"