version: '3.7'
networks:
  db_net:
  dockernetwork:
    external: true
services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
    - 27017:27017
    networks:
      - db_net
  mongo-ui:
    container_name: mongo-ui
    image: mongo-express
    ports:
    - 8081:8081
    depends_on:
    - mongo
    networks:
      - db_net
  parties:
    container_name: parties
    build: .
    ports:
    - "8000:80"
    environment:
    - MONGO_HOST=mongo
    networks:
      - dockernetwork
      - db_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.parties.rule=Host(`test.dice-arena.com:8000`)"
      - "traefik.http.routers.parties.entrypoints=https"
      - "traefik.http.routers.parties.tls=true"
      - "traefik.http.routers.parties.tls.certresolver=letsencrypt"
      - "traefik.http.services.parties.loadbalancer.server.port=8000"