name: 'test workflow'
on: push
jobs:
  vuejs-test-unitaire:
    runs-on: ubuntu:latest
    steps:
      - name: recuperation du repo
        uses: actions/checkout@v2
      - name: install nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: execution tests
        run: npm run test:unit
