name: 'test workflow'
on: push
jobs:
  vuejs-test-unitaire:
    runs-on: ubuntu-latest
    steps:
      - name: recuperation du repo
        uses: actions/checkout@v2
      - name: install nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: installation des dépendances
        run: npm i
      - name: execution des tests
        run: npm run test:unit
  toto:
    needs: vuejs-test-unitaire
    runs-on: ubuntu-latest
    steps:
      - run: echo 'toto'
