version: '3.7'

services:
  front:
    container_name: front
    build: ./frontend
    ports:
    - "8080:8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.front.rule=HostRegexp(test.arena.com, {subdomain:[a-z]+}.test.arena.com)"
      - "traefik.http.routers.front.entrypoints=websecure"
      - "traefik.http.routers.front.tls.certresolver=letsencrypt"
      - "traefik.http.services.front.loadbalancer.server.port=8080"