version: '3.7'
networks:
  dockernetwork:
    external: true
services:
  front:
    container_name: front
    build: ./frontend
    ports:
    - "8080:8080"
    networks:
      - dockernetwork
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.front.rule=Host(`test.dice-arena.com`)"
      - "traefik.http.routers.front.entrypoints=https"
      - "traefik.http.routers.front.tls=true"
      - "traefik.http.routers.front.tls.certresolver=letsencrypt"
      - "traefik.http.services.front.loadbalancer.server.port=8080"
